[9] POST /todos
pdany1116/todo_api pull request #23
Opened 2022-07-13 10:25 UTC by pdany1116

#### Description

Create a todo via POST /todos.

#### [9](https://trello.com/c/2nYHdEWq/9-post-todos)

#### Related PRs

## Steps to Test or Reproduce

1. Follow test steps in README.
2. All tests should pass.
## Risks

2022-07-13 12:14 UTC, cazacutudor requested changes

2022-07-13 12:14 UTC, cazacutudor commented on app/controllers/todos_controller.rb
> +    todo.url = "/todos/#{todo.id}"
The URL should be computed in the serializer.

2022-07-13 12:14 UTC, cazacutudor commented on app/controllers/todos_controller.rb
> +    render json: '', status: :unprocessable_entity
We should respond with the validation errors

2022-07-13 12:14 UTC, cazacutudor commented on db/migrate/20220713104011_set_default_values.rb
> +      change_column_default :todos, :completed, from: nil, to: false
I think change_column_default should work outside of change_table. What's the scope of these functions?

2022-07-13 12:14 UTC, cazacutudor commented on app/controllers/todos_controller.rb
> +  def create
Integration specs missing for todo creation

2022-07-13 12:14 UTC, cazacutudor commented on features/support/todo_helpers.rb
> +    post todos_path, attributes_for(:todo).slice(:title)
Why we are not including the title?

2022-07-13 12:17 UTC, pdany1116 commented on db/migrate/20220713104011_set_default_values.rb
> +      change_column_default :todos, :completed, from: nil, to: false
Rubocop was complaining about altering the table in multiple operations (here 2). By specifying `bulk: true` to `change_table`, these 2 operations will be transformed in a single alter operation.

2022-07-13 12:20 UTC, pdany1116 commented on app/controllers/todos_controller.rb
> +    render json: '', status: :unprocessable_entity
I thought about it. Should we do this in another ticket?

2022-07-13 12:21 UTC, pdany1116 commented on features/support/todo_helpers.rb
> +    post todos_path, attributes_for(:todo).slice(:title)
We are including only the title. `slice` returns only specified keys from hash.

2022-07-15 10:35 UTC, cazacutudor approved these changes

2022-07-15 10:55 UTC, merged